--- #YAML:1.0
name:               POE-Loop-Tk
version:            1.302
abstract:           Tk event loop support for POE.
author:
    - Rocco Caputo <rcaputo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
    POE::Test::Loops:     1.021
build_requires:
    ExtUtils::MakeMaker:  0
    POE::Test::Loops:     1.021
requires:
    POE:               1.007
    POE::Test::Loops:  1.021
    Tk:                804.028
resources:
    license:     http://dev.perl.org/licenses/
    repository:  https://poe.svn.sourceforge.net/svnroot/poe/trunk/polo-tk
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
